### ISSUE TITLE
Developer notifications

### ISSUE THREAD

**Issue by nadeensami** [gdsc21/gdsc#16]
Developers should receive a notification when:
1. A non-profit accepts a request to join a project they applied for (acceptance notifications)
2. A non-profit requests for them to join a project (request notifications)

### Front-end
- Notifications should be displayed in chronological order (most recent at the top)
- Notifications are "accordion" style -- when you click on them, they expand or contract
- [ ] Add a notifications tab on the developer dashboard
- [ ] Add a notification component for acceptance notifications
   - [ ] Different when the developer has read it
- [ ] Add a notification component for request notifications
  - [ ] Have "accept" and "decline" buttons
  - [ ] Different when the developer has responded to it (+ no accept/decline)

### Back-end
- [ ] Have an array of notifications associated with each developer. sorted by date (most recent last), each notification having the following properties:
   - `type` - string: either "acceptance" or "request"
   -  `date` - Date: the time that the notification was created
   -  `project` - object: the project object with some basic project information, including non-profit information and project url
   -  **acceptance** `read` - boolean: did the developer see it? (changed when developer checks notifications tab)
   -  **acceptance** `accepted` - boolean: what was the result of the application?
      - true indicates that the non-profit accepted the request
      - false indicates that the non-profit has declined the request
      - null indicates that the non-profit has not responded yet
   -  **request** `accepted` - boolean: did the developer respond to it? (changed when developer either accepts or declines the request)
      - true indicates that the developer accepted the request
      - false indicates that the developer has declined the request
      - null indicates that the developer has not responded yet
- [ ] Create a function that sends an acceptance notification to the non-profit when the developer responds to their request notification.

(Yes, there are two different `accepted` variables but they are different depending on the type of notification – for an acceptance, it's what the result of their (the developer's) request to join a non-profit is; for a request, it's what the current developer's response is.)

**Comment by timolegros** [comment]
The notification system is no longer relevant as we have transitioned to an application-based system without conventional live notifications.
