### ISSUE TITLE
Non-profit Notifications

### ISSUE THREAD

**Issue by nadeensami** [gdsc21/gdsc#17]
Non-profits should receive a notification when:
1. A developer accepts a request to join their project (acceptance notifications)
2. A developer requests to join a project of theirs (request notifications)

### Front-end
- Notifications should be displayed in chronological order (most recent at the top)
- Notifications are "accordion" style -- when you click on them, they expand or contract
- [ ] Add a notifications tab on the non-profit dashboard
- [ ] Add a notification component for acceptance notifications
   - [ ] Different when the non-profit has read it
- [ ] Add a notification component for request notifications
  - [ ] Have "accept" and "decline" buttons
  - [ ] Different when the non-profit has responded to it (+ no accept/decline)

### Back-end
- [ ] Have an array of notifications associated with each non-profit, sorted by date (most recent last), each notification having the following properties:
   - `type` - string: either "acceptance" or "request"
   -  `date` - Date: the time that the notification was created
   -  `project` - object: the project object with some basic project information, including non-profit information and project url
   - `developer` - object: the developer for whom this notification is about
   -  **acceptance** `read` - boolean: did the non-profit see it? (changed when non-profit checks notifications tab)
   -  **acceptance** `accepted` - boolean: what was the result of the application?
      - true indicates that the developer accepted the request
      - false indicates that the developer has declined the request
      - null indicates that the developer has not responded yet
   -  **request** `accepted` - boolean: did the non-profit respond to it? (changed when non-profit either accepts or declines the request)
      - true indicates that the non-profit accepted the request
      - false indicates that the non-profit has declined the request
      - null indicates that the non-profit has not responded yet
- [ ] Create a function that sends an acceptance notification to the developer when the non-profit responds to a request notification.

(Yes, there are two different `accepted` variables but they are different depending on the type of notification – for an acceptance, it's what the result of their (the non-profit's) request for a developer to join is; for a request, it's what the non-profit/s response is.)

**Comment by timolegros** [comment]
This issue is outdated/irrelevant. New notification/application system is being developed and no longer aligns with the specifications in this issue.
